### ISSUE TITLE
Question about geomstats version

### ISSUE THREAD

**Issue by cr42yhc1** [anshulbshah/HaLP#1]
Thank you for your contribution! I have encountered some issues with geomstats during my experiments, specifically in the HaLP/moco/builder_single_modality_halp.py file at line 86 where the RiemannianKMeans class is used. According to the official documentation (https://geomstats.github.io/api/geomstats.learning.html#geomstats.learning.kmeans.RiemannianKMeans), there is no init_step parameter available. Additionally, at line 84, the Hypersphere class does not seem to have a metric attribute. These inconsistencies have caused errors in the program when updating the prototypes. Could you please provide information about the geomstats version you are using in your environment or suggest a compatible codebase for the current version 2.7.0 of geomstats? Your assistance would be greatly appreciated.

**Comment by anshulbshah** [comment]
Hi, thanks for your interest in our work. I was using geomstats 2.5.0 which has the metric [attribute](https://github.com/geomstats/geomstats/blob/2.5.0/geomstats/learning/kmeans.py). I can look into updating the codebase for the new geomstats version if downgrading does not work for you. [This](https://github.com/geomstats/geomstats/blob/master/examples/plot_kmeans_manifolds.py) reference can help in modifying the code for new geomstats if you want to use 2.7.0.

**Comment by cr42yhc1** [comment]
Thank you for your response. After downgrading geomstats, it works now.
